export const generateCategoryDescription = (categoryName: string): string[] => {
    return [
        `Welcome to the ultimate destination for <strong>${categoryName} wallpapers</strong>. At WallpapersFlix, we pride ourselves on curating the most extensive and high-quality collection of background images tailored specifically for fans of ${categoryName}. Whether you are a long-time enthusiast or just discovering the beauty of this genre, our gallery offers something unique for everyone. We understand that a wallpaper is more than just an image; it's a reflection of your personality, your mood, and your style. That's why we have dedicated countless hours to handpicking only the finest ${categoryName} visuals that will transform your screens into digital masterpieces.`,

        `Our collection features a diverse range of <strong>4K and HD ${categoryName} backgrounds</strong> that are perfect for any device. From the crisp, high-resolution displays of modern desktops and laptops to the vibrant screens of the latest smartphones like the iPhone, Samsung Galaxy, and Google Pixel, our wallpapers are optimized to look stunning everywhere. We ensure that every image maintains its clarity and color depth, so you can enjoy every detail of your favorite ${categoryName} scenes. Whether you prefer minimalist designs, dynamic action shots, or serene artistic interpretations, you will find a wallpaper that perfectly matches your aesthetic preferences.`,

        `In today's digital age, customization is key. Your device is your constant companion, and changing your wallpaper is one of the easiest ways to keep your digital environment fresh and inspiring. Our <strong>${categoryName} wallpapers</strong> are designed to be versatile. Use them as your home screen to greet you with inspiration every time you unlock your phone, or set them as your lock screen to make a bold statement. They are also perfect for social media backgrounds, profile headers, or even as inspiration for your own creative projects. The possibilities are endless when you have access to such a vast library of premium quality images.`,

        `We are constantly updating our database with the latest and trending <strong>${categoryName} images</strong>. Our team of editors keeps a close eye on the latest trends, releases, and artistic movements within the ${categoryName} world to ensure that you always have access to the freshest content. You no longer need to scour the internet for hours looking for high-quality images; we have brought them all together in one convenient place. All our wallpapers are available for free download, making it easier than ever to build your own personal collection of favorites.`,

        `Experience the difference of true quality with WallpapersFlix. We believe that everyone deserves access to beautiful art and design without barriers. That's why our <strong>${categoryName} background collection</strong> is completely free to access and download. No hidden fees, no subscriptions—just pure, high-quality visual content. Dive into our categories, explore the sub-genres, and discover the perfect image that speaks to you. Upgrade your digital experience today with the best ${categoryName} wallpapers available online.`
    ];
};
